# Generated by Django 5.2.17 on 2026-09-30 02:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(help_text='Identificador usado na URL, sem espaços', max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('resumo', models.CharField(blank=True, help_text='Aparece na listagem. Se vazio, usamos o início do texto.', max_length=300)),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('situacao', models.CharField(choices=[('RA', 'Rascunho'), ('PU', 'Publicado')], default='RA', max_length=2, verbose_name='Situação')),
                ('publicado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='artigos.categoria', verbose_name='Categoria')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='artigos.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-publicado_em'],
            },
        ),
    ]
