# Generated by Django 5.2.17 on 2026-09-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='capa',
            field=models.ImageField(blank=True, upload_to='capas/', verbose_name='Imagem de capa'),
        ),
    ]
